services:
  - type: web
    name: iotflask
    env: python
    repo: https://github.com/salahchaibi/iotflask
    branch: main  # Adjust if your default branch is not 'main'
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      if [ ! -f migrations/ ]; then
        flask db init
      fi
      flask db migrate -m "Ajout des modèles de base" || echo "No changes detected in migrations"
      flask db upgrade
      flask run --host=0.0.0.0
    plan: free
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        value: "postgresql://app_user:Mxa3w4rHY64GorhVZWN18K2BvWHCSAFa@dpg-cu0mq4btq21c73ctbmqg-a:5432/iotflask_db"  # Use Render's environment variables for database connection
  - type: web
    name: iotflask-front
    runtime: static
    repo: https://github.com/salahchaibi/iotfront
    staticPublishPath: ./static

databases:
  - name: iotflask-db
    plan: free
    region: oregon
    postgresMajorVersion: 16
    user: app_user
